### ISSUE TITLE
Everything is slow after activating shackle-mode from latest melpa

### ISSUE THREAD

**Issue by fourier** [wasamasa/shackle#13]
Starting Emacs in windowed mode with this simple **init.el**:
```elisp
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")))

(package-initialize)
(require 'shackle)
(shackle-mode)
```
lead to unresponsive behavior of Emacs: every operation takes too long to perform. For example running **erc** takes like 8 seconds.
No problem with Emacs started with -nw option.
Emacs from MacPorts on OSX 10.10
```
/Applications/MacPorts/Emacs.app/Contents/MacOS/Emacs --version
GNU Emacs 24.4.1
Copyright (C) 2014 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by fourier** [comment]
The problem was caused by weird character in **shackle-lighter**
The solution is to add something like
```elisp
(setq shackle-lighter "s")
```
before calling the ```(shackle-mode)```

**Comment by wasamasa** [comment]
Could you try using other OS X builds whether they exhibit the same issue? There's plenty of them, including the official one, Brew, emacsforosx.com, Railwaycat, ...

**Comment by fourier** [comment]
Same problem with http://emacsformacosx.com/

**Comment by wasamasa** [comment]
What about the Railwaycat port?

https://github.com/railwaycat/emacs-mac-port/wiki/Downloads
https://github.com/railwaycat/homebrew-emacsmacport

**Comment by fourier** [comment]
Better wit Railwaycat port (erc starts fast enough), but ```shackle-mode``` still slow.

**Comment by wasamasa** [comment]
Well, that is a pretty weird issue, almost bordering to an Emacs bug if the mere act of selecting a glyph in the Emoji range causes extreme slowdowns. I'd report it to one of the persons involved in either any of the OS X ports or the official Emacs support for it.

**Comment by wasamasa** [comment]
@fourier Did you report a bug for this behaviour yet?

**Comment by fourier** [comment]
No, I don't know where to. And most likely since it is a Mac version bug, nobody will care

**Comment by wasamasa** [comment]
Well, with the regular `M-x report-emacs-bug`, it might yield a more interesting discussion than this one (or get ignored), so I reckon it's worth a try.
