### ISSUE TITLE
Is it possible to set a rule to open a buffer in one of the existing windows other than the current one?

### ISSUE THREAD

**Issue by kaushalmodi** [wasamasa/shackle#17]
I'd like to open the \*Help\* buffers in an already open window to the right/left but not the current one. Is that possible? Or can you implement that feature?

This is what I have (I am not showing the other rules I have for simplicity):

``` el
(setq shackle-rules '(
                          ;; Help
                          ("*Help*"
                           :align right
                           :popup nil
                           :select t)))
```

Here is the desired behavior in more detail:
- Select the \*Help\* buffer when it opens
- If the frame has only one window, split a window to the right and show \*Help\* buffer in that. Close that window when I quit Help.
- If the frame has more than one window, do NOT split any more windows. Instead, show Help in one of the open windows (other than the current one). Quitting Help in that case should not close that window.

**Comment by kaushalmodi** [comment]
Solved part of my problem with the help of this:

```el
(define-key special-mode-map (kbd "q") (λ (quit-window :kill)))
```
Still need help on how to reuse one of the open windows if 2 or more windows are already open.

**Comment by kaushalmodi** [comment]
For now, this feels like a sane option:

``` el
("*Help*"
                           :align below
                           :ratio 0.3
                           :select t)
```

**Comment by wasamasa** [comment]
Currently it's hardcoded that if a window is already displaying a buffer and `display-buffer` is used on that buffer, its window is used for the operation (and optionally selected afterwards).

The window management strategy you're proposing here sounds mostly like what an unconfigured helm setup is doing (as it splits an only window and uses the resulting window or reuses the other window). Can you confirm this?

**Comment by kaushalmodi** [comment]
I am not using Helm.. 

I am talking about the behavior of the \*Help\* windows that open on doing `C-h v`, `C-h f`, etc

**Comment by wasamasa** [comment]
Sure, I get that you wish to change the behaviour of the help windows, what I'm asking for is whether the behaviour you wish to have instead can be modeled after something existing, like helm for example (because I could just look at its code and use that).

Another thing I have to think of is whether I'll turn that into a proper action and give it a name or instead add generic support for implementing your own actions.

**Comment by kaushalmodi** [comment]
I haven't used helm much but I just tried it out again to confirm.

Yes, helm does exactly that:

- If the frame has 2 windows and I am in window 1, it shows Helm candidates in window 2.
- If the frame has 1 window, then it pops up a temporary window to show the candidates.

Now for the case of 3 or more windows per frame, I am not sure how Helm behaves as I haven't used it extensively (I am actually going to uninstall it after this). But something like the below can probably be done?

- For frame with 3 or more windows, give the user to pick the widest or tallest of the windows other than the current one.

**Comment by wasamasa** [comment]
For more than two windows, helm is using the window `C-x o` would use AKA the *other* window.

**Comment by kaushalmodi** [comment]
@wasamasa Thanks for looking into this!

> For more than two windows, helm is using the window C-x o would use AKA the other window.

I am fine with that. As it is, I very rarely have 3 windows open in a frame unless something like a Help buffer is opened temporarily.

**Comment by wasamasa** [comment]
OK, I think I've got a name `:other`, clearly defined behaviour, an extra user wishing for that feature (albeit for frames) and [example](http://emacs.stackexchange.com/questions/12747/how-to-conditionally-reuse-the-current-window-to-display-a-buffer) [code]{https://groups.google.com/forum/#!msg/gnu.emacs.help/EuRyr8P9p0I/7jLczIxXFHAJ)!

**Comment by wasamasa** [comment]
I've implemented the `:other` keyword now, it can be used on its own or in combination with `:frame` to have the described behaviour for frames.

    (setq shackle-rules '(("*Help*" :other t :select t)))

Still need to investigate into the behaviour of `q` though as in my tests it closes the window as well.

**Comment by kaushalmodi** [comment]
> Still need to investigate into the behaviour of q though as in my tests it closes the help window as well.

`q` is bound to `quit-window` in `special-mode-map` so it will kill the window and bury the buffer.

I have this in my init if you are interested:

```el
;; Special Mode Map
;; `special-mode' is a read-only major mode (simple.el)
(define-key special-mode-map (kbd "q") (lambda (interactive) (quit-window :kill))) ; quit + kill
(define-key special-mode-map (kbd "y") #'quit-window) ; quit + bury
(define-key special-mode-map (kbd "z") #'quit-window) ; quit + bury
(define-key special-mode-map (kbd "k") (lambda (interactive) (kill-buffer (current-buffer)))) ; only kill
```

**Comment by wasamasa** [comment]
I already have a workaround used by the `:same` key:

```elisp
    (set-window-parameter (selected-window) 'quit-restore nil)
```

Maybe that could be taken out in favour of an `:inhibit-quit` key that works similiar to `:select` where it would make sense.

**Comment by wasamasa** [comment]
`:inhibit-window-quit` is a thing now and can be used to achieve the final part of your desired behaviour.

**Comment by kaushalmodi** [comment]
Awesome! Now the only `display-buffer-alist` stuff I have in my emacs init is one statement what I use to open Shell command buffers in background ( https://github.com/wasamasa/shackle/issues/18 ). All set other than that :)

My current state of `shackle-rules`: https://github.com/kaushalmodi/.emacs.d/blob/b6d701af9bb10c1f4d8022fa229804cb6535e1ac/setup-files/setup-shackle.el#L14-L32

**Comment by kaushalmodi** [comment]
`:inhibit-window-quit` works great, thanks!
I now use that with \*Help\* and \*Messages\* buffers.
