### ISSUE TITLE
Support for `display-buffer-no-window`

### ISSUE THREAD

**Issue by kaushalmodi** [wasamasa/shackle#18]
Hi,

Sorry for the stream of issues I am opening today.

I am trying to see if I can use this to replace all of the `display-buffer-alist` and `popwin` customizations in my emacs init.

For this request, I was trying to get rid of the below from my init but I see that currently `shackle` doesn't have an option to open a buffer in the background (or does it?). For example, I would always like to open the Async Shell Command buffers to open in the background and not occupy any of the visible windows:
``` el
;; Don't display async command execution windows
;; http://emacs.stackexchange.com/a/5554/115
(add-to-list 'display-buffer-alist
             (cons "\\*Async Shell Command\\*.*"
                   (cons #'display-buffer-no-window nil)))
```

**Comment by kaushalmodi** [comment]
Probably this issue is covered by this issue ( https://github.com/wasamasa/shackle/issues/15 ) you already opened.

**Comment by wasamasa** [comment]
Yup, that's right.  I'd like to gather other display actions there to have an idea whether there is a need for special actions or implementing a generic interface for more obscure customization suffices.

**Comment by kaushalmodi** [comment]
The `display-buffer-no-window` option is still not implemented; is that correct?

The `display-buffer-alist` in the above example makes sure that the buffer opens in the background (not in any of the visible windows).

**Comment by wasamasa** [comment]
That's right. I think I'll settle for implementing an `:ignore` as I've already implemented the `:other` key and nothing else worthwhile looking popped up.

**Comment by kaushalmodi** [comment]
Minor suggestion: How about calling it `:background`; as in that window will always open in the background.

**Comment by wasamasa** [comment]
Well, that's a bit longish and suggests there's `:foreground` which isn't a thing.
