### ISSUE TITLE
Copy/paste error?

### ISSUE THREAD

**Issue by kaushalmodi** [wasamasa/shackle#19]
You have this at the [following lines][1] (as of the current version).

```el
                                   (:same boolean)
                                    (:popup boolean)
                                    (:same boolean)
```

Also that `defcustom` docstring and `:value-type` are missing the new `:other` keyword.

[1]: https://github.com/wasamasa/shackle/blob/master/shackle.el#L139-L141

**Comment by wasamasa** [comment]
Thanks.
