### ISSUE TITLE
Understanding `:same` and `:popup`

### ISSUE THREAD

**Issue by kaushalmodi** [wasamasa/shackle#21]
From the readme,

> :same and t: Display buffer in the current window.
> :popup and t: Pop up a new window instead of displaying the buffer in the current one.

It feels as if `:same t` is the same as `:popup nil` and vice-versa.

Can you please give some examples to better understand these keywords? Probably an example where you would want to set both to nil or both to t?

**Comment by wasamasa** [comment]
`:same` and `:popup` are mutually exclusive, so using both wouldn't make any sense. If you for example encounter elisp code making use of `display-buffer` or `pop-to-buffer` and wish it had used `switch-to-buffer` instead, you can use `:same` to achieve this effect. The opposite applies to `:popup` as it can be used to make something using `switch-to-buffer` result in a popup similiar to what `display-buffer` or `pop-to-buffer` would do.

**Comment by kaushalmodi** [comment]
Thanks for the explanation. This is very helpful.
