### ISSUE TITLE
how to set special-mode according to a regexp?

### ISSUE THREAD

**Issue by QiangF** [wasamasa/shackle#22]
Hello,
Some buffers can be read only and if they are put in special-mode, we can quit them with q. 
Is it possible to add another keyword \:special?
Thank you for your consideration.

**Comment by wasamasa** [comment]
Well, that's not really window management you're doing there. This can be solved in a much simpler manner by either matching by their mode or file name.

```elisp
(add-hook 'my-buffer-major-mode 'special-mode)
```

```elisp
(add-to-list 'auto-mode-alist '(my-file-name . special-mode))
```

**Comment by wasamasa** [comment]
Another reason for this is because this task doesn't really match shackle's API. First, it executes things on windows (not buffers), second this can be done in a much more elegant manner by using something hook-like at the right level instead of reinventing hooks.
