### ISSUE TITLE
Allow for more complex behaviour by using predicates

### ISSUE THREAD

**Issue by wasamasa** [wasamasa/shackle#23]
@kovrik suggested a change for allowing more fine-grained behaviour for their ERC setup. Using the `:same` keyword is a good start, but is somewhat icky as selecting a non-ERC window while it is still loading up will switch its buffer out for an ERC buffer. A possible solution to this is linking a predicate to the keyword so that the keyword is only considered if the predicate holds true.

I can imagine a syntax along the lines of the alternatives syntax in conditions which is simply a list of symbols or strings (instead of a symbol or string).  Doing something similiar in an action could work by simply wrapping the keyword in a list and letting a predicate follow. I'm not sure on the specific syntax of the predicate, but a rule could look like `(erc-mode (:same erc-window-selected) (:other erc-window-not-selected))`.

**Comment by kovrik** [comment]
Or maybe make it cond-like (but I don't know if it is possible to implement it that way and I don't know what arguments are being passed):

Example:
```elisp
;; shackle rules for erc-mode
(erc-mode (cond
           ((condition1) '(:other t))
           ((condition2) '(:other t :ratio 0.5))
           (else         '(:same t))))
```

**Comment by wasamasa** [comment]
Hmm, at that point it might make more sense to let people write their own function and leverage the existing ones for actions.

**Comment by wasamasa** [comment]
I can see two ways of custom code to work out, one would be to introduce a `:custom` keyword in actions that allows you to provide a function name or lambda to be called with `BUFFER-OR-NAME`, `ALIST` and `PLIST`. The function can then check for existing windows and buffer-local values of the currently selected buffer, but I've found that such functions needlessly duplicate the condition part.

```elisp
(defun my-shackle-circe (buffer alist plist)
  (if (memq major-mode '(circe-server-mode circe-channel-mode circe-query-mode))
      (shackle--display-buffer-same buffer alist)
    (shackle--display-buffer-popup-window buffer alist plist)))

(setq shackle-rules '(((circe-server-mode circe-channel-mode circe-query-mode)
                       :custom my-shackle-circe)))
```

The alternative would be to make conditions more flexible. As simple values can't really be used for that and lists already have a special meaning as compound values, I'd extend it to a special case that recognized `:custom` as first item and uses a function name or lambda as second.  The action would stay the way it is.

```elisp
(defun my-shackle-circe (buffer alist plist)
  (memq major-mode '(circe-server-mode circe-channel-mode circe-query-mode)))

(setq shackle-rules '(((:custom my-shackle-circe) :same t)
                      ((circe-server-mode circe-channel-mode circe-query-mode) :popup t)))

**Comment by wasamasa** [comment]
FWIW, you can't adapt this code for ERC yet because it sets the current buffer to the server buffer before displaying the window. Therefore it's not possible to determine the major mode of the buffer that was selected before unless you patch ERC. Another issue I've found is a bit less serious, you'll need to customize the reporting type to unconditionally use `display-buffer`, this should be doable with `erc-join-buffer` set to `window-noselect`.
