### ISSUE TITLE
Cannot get any functionality

### ISSUE THREAD

**Issue by drwebb** [wasamasa/shackle#24]
Hi, I've tried playing around with this package a bit and I want to switch from popwin, unfortunately I can't even get started.

I tried debugging by running `emacs -nw -q` then evaluating the following in the scratch buffer

```
(setq package-user-dir "~/.emacs.d/elpa/")
(package-initialize)
(require 'shackle)
(setq shackle-rules
      '((t :same t)))
(shackle-mode 1)
```

Then a command that pops up a new window such as `M-x help-for-help` does in fact pop up a new window.

My emacs version
```
GNU Emacs 25.0.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.3) of 2015-06-04 on \
church
```

**Comment by wasamasa** [comment]
Oh snap, I forgot changing one of the examples. You'd no longer use `t` as condition, but rather customize `shackle-default-rule`:

```elisp
(setq shackle-default-rule '(:same t))
```

**Comment by drwebb** [comment]
Thanks, at least I can verify that this is working!
