### ISSUE TITLE
shackle-lighter defaults to a Unicode character which is not in all fonts

### ISSUE THREAD

**Issue by PhilipDaniels** [wasamasa/shackle#31]
This causes the modeline to almost double in height because it prints as a box with "2603" in it. This character is not present in Consolas, for example. Please default to something less esoteric like "sm".

**Comment by wasamasa** [comment]
As the issue came up numerous times before and the Emacs core developers didn't express any interest in actually fixing or simplifying the setup of font fallback, I've just removed lighters in all of my packages not needing those.  Good riddance.
