### ISSUE TITLE
cannot get shackle to popup ielm

### ISSUE THREAD

**Issue by hydandata** [wasamasa/shackle#33]
Tried setting it the same way as shell and eshell, both of which work as expected:
```elisp
(setq shackle-default-rule '(:select t)
      shackle-rules
      '((("*shell*" "*eshell*" "*ielm*") :popup t)
        (compilation-mode :noselect t)))
```
Did not work, also tried setting it for (emacs-)lisp-interacton-mode and comint-mode, but still it switches the current window to ielm buffer instead of poping up. Not sure whether this is an issue with shackle or ielm.

**Comment by wasamasa** [comment]
Thanks for the mention.  I've discovered the same thing before and handed in [a bug](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21198).  This should be fixed as of Emacs 25.  If you wish it to be fixed in an earlier version, just use the patch there.

**Comment by dieggsy** [comment]
@wasamasa i'm still seeing this issue - it works when I only have one window open and call ielm. If I have more than one window open, ielm uses the current one.

**Comment by wasamasa** [comment]
This is a different bug though, the behavior of Emacs changed and Shackle would have to change again.

**Comment by dieggsy** [comment]
@wasamasa ah, would you prefer a new issue?

**Comment by wasamasa** [comment]
Yes.
