### ISSUE TITLE
Can't make it work with helm-swoop

### ISSUE THREAD

**Issue by sandric** [wasamasa/shackle#35]
I tried all the variants but still can not make it work with helm-swoop package... I found those examples but they do nothing to helm-swoop [sorry for japanese, don't know what its saying](http://rubikitch.com/2015/03/10/shackle/). I tried also the variant with reqexp as suggested in example:

```elisp
(use-package shackle
  :ensure t
  :init (progn
          (require 'shackle)
          (add-to-list 'shackle-rules
                       '("\\`\\*helm.*?\\*\\'" :regexp t :align t :size 0.4))
          (add-to-list 'shackle-rules
                       '("\\`\\*Helm.*?\\*\\'" :regexp t :align t :size 0.4))))
```

But this still doesn't make nothing to swoop window but working with helm window though. Do I loose smth? thx.

**Comment by wasamasa** [comment]
I've found a workaround that makes helm-swoop play nice with shackle:

```elisp
(setq helm-swoop-split-window-function 'display-buffer)
```

And with that, it is subject to its rules again.  Please confirm whether it works for you.
