### ISSUE TITLE
Shackle not matching dired-mode

### ISSUE THREAD

**Issue by sandric** [wasamasa/shackle#36]
I can not figure out why does shackle failing recognizing dired-mode. Here's my config:
```elisp
(use-package shackle
  :ensure t
  :config (progn
            (setq shackle-rules
                  '(
                    (help-mode :custom sandric/shackle-in-right-pane)
                    (dired-mode :custom sandric/shackle-in-right-pane)
                    ("*Ibuffer*" :align below :ratio 0.3)
                    ))
            (shackle-mode t)))
```
For help-mode everything works fine - function evaluated. For dired-mode its strangely not. I checked the `major-mode` output for buffer I open with `dired-jump` shortcut - its `dired-mode`, but it does not a match for shackle. Can smbd reproduce that?

**Comment by wasamasa** [comment]
How exactly are you opening a dired buffer?

**Comment by sandric** [comment]
No, I don't use `dired-other-window`, I open it with global keybinding, here:
```elisp
(global-set-key (kbd "S-C-H-v") 'dired-jump)
```
And its always open dired mode in the same window with only this. I made obvious fix to make dired buffer to be opened in right pane with this as for now:
```elisp
(advice-add 'dired :before 'sandric/select-right-pane)
```
It don't really fit, but if anybody had the same issue with dired here's quick fix.

**Comment by sandric** [comment]
Is there's a proper way then to call dired buffer to fix this? I mean to eliminate `switch-to-buffer` thing.

**Comment by wasamasa** [comment]
Yes, I've edited it into my previous reply.

**Comment by sandric** [comment]
Oh, I see now, thx, I tried to change default dired function to use `pop-to-buffer` and now it seems to work with ranger. The problem is as I went through dired.el and dired-x.el is that there's a lot of `switch-to-buffer` actually... Ok I'll then add a bug request with link to this issue. One question - where to ask (I never issued for default emacs bugs before)? Is emacs repo is on github?

**Comment by wasamasa** [comment]
Use `M-x report-emacs-bug` for this or if you dare, send an email directly to `bug-gnu-emacs@gnu.org`.
