### ISSUE TITLE
Add option for default-alignment to change based on window width?

### ISSUE THREAD

**Issue by sooheon** [wasamasa/shackle#38]
Would it be possible to allow the :align keyword in shackle rules or the shackle-default-alignment variable to take a function like `(if (> (window-width) 160) 'right 'below)`, so that alignment is bottom most of the time, unless fullscreen, in which case it becomes right?

**Comment by wasamasa** [comment]
That is not a function, but I get the gist.

**Comment by sooheon** [comment]
Yep should've said expression. I was thinking along the lines of the `(:eval ...)` you can do in the mode-line-format.

**Comment by wasamasa** [comment]
You can now use `:align (lambda () (if (> (window-width) 160) 'right 'below))`.

**Comment by sooheon** [comment]
Thanks!
