### ISSUE TITLE
Can not select the *Pp Eval Output* buffer

### ISSUE THREAD

**Issue by Yevgnen** [wasamasa/shackle#41]
Hi,

With the following test snippet on `emacs -Q`

```
(package-initialize)
(require 'shackle)
(setq shackle-default-alignment 'below
      shackle-rules `(("*Help*" :align below :select t)
		      ("*Messages*" :align below :select t)
		      ("*Pp Eval Output*" :align below :select t)))
(shackle-mode 1)

;; Eval the following sexp to get a *Pp Eval Output* buffer
;; (pp-eval-expression `,(print 'shackle-rules))
```

the `*Pp Eval Output*` buffer seems can not be selected. I want to select the window because I've added an advice to enable view mode on it so that I can close the window by `q`.

Could you help me on this ? Thanks !

**Comment by wasamasa** [comment]
I can reproduce this.

If you take a look at the sources of `pp-eval-expression` (with `M-x find-function`), you'll see it's using `pp-display-expression` which uses `with-output-to-temp-buffer` to display temporary results in a new window.  According to its documentation (which you can read with `F1 f`) this *does* normally use `display-buffer` (which allows shackle to customize how popups are handled), however this doesn't happen as the function overrides `temp-buffer-show-function` and does not use `display-buffer` anymore.

The code of that replacement is really weird.  Perhaps it's worth a bug report via `M-x report-emacs-bug`...
