### ISSUE TITLE
Temporarily set ignore-window-parameters to t

### ISSUE THREAD

**Issue by sw9** [wasamasa/shackle#43]
I'm currently using shackle mode with neotree. Neotree sets window-side parameter. Thus, whenever shackle tries to split the window, I get the following error message: "split-window: Cannot split side window or parent of side window." I think Shackle should probably set ignore-window-parameters to t, split the window, and then reset this parameter when you quit the window.

**Comment by wasamasa** [comment]
Under which conditions do you get the problem?  Is it with the align action?

**Comment by sw9** [comment]
hmm yes, it appears I have :align t :size 0.4 for shackle rules

**Comment by wasamasa** [comment]
Thanks for mentioning this, it looks like align isn't the only action needing this, so I added a let-binding for that variable.
