### ISSUE TITLE
Shackle Rules Don't Apply to mu4e

### ISSUE THREAD

**Issue by naclander** [wasamasa/shackle#44]
In mu4e, I am trying to get the `mu4e-view` buffer, when opened from the `mu4e-headers` buffer, to only take up 40% of the screen.

I have seemingly tried every possible combination of regex and I can't seem to apply shackle rules to windows/buffers in mu4e. So at this point, I'm concerned it might be a bug in Shackle. 

My concern is that mu4e might be opening intermiddiate buffers, and so the Shackle rules would not apply? Would buffers changing disable certain Shackle rules? 

For example, I've tried the following rules:

```elisp
(setq shackle-rules '(("\\`\\*mu4e.*?\\*\\'" :regexp t :align t :size 0.4)
                      ("mu4e-loading" :regexp t :popup t :select t :same t size: 0.4)
                      ("mu4e-view" :regexp t size: 0.4)
                      ("mu4e" :regexp t :popup t :select t :same t size: 0.4)
                      ("view" :regexp t :popup t :select t :same t size: 0.4)))
```

And none seem to have any effect on the `mu4e-view` buffer when its opened in a new window.

I did notice that mu4e opens an intermiddiate buffer right before `mu4e-view` loads ( but in the same window ). i.e. `mu4e-loading` is sometimes shown first. but I figured my regex for `mu4e` would catch that. 

Let me know if there are other ways I can debug this, or if you need any more information. 

Thanks for the great work on this package so far.

**Comment by wasamasa** [comment]
Shackle won't ever work on it because `mu4e-view` doesn't use `display-buffer` or any of its variations at all: https://github.com/djcb/mu/blob/2811370d7efecfc86031e1d736c0c08a3bcd59a5/mu4e/mu4e-view.el#L319

**Comment by naclander** [comment]
@wasamasa is there a reason shackle doesn't work when calling `switch-to-buffer`? Is it worth creating an issue to track this?

**Comment by wasamasa** [comment]
It's by design.  Buffers displayed by `display-buffer` and such can be displayed in any way the user customized them to, buffers displayed by the lower level procedures cannot.  To quote the README:

>  If you should ever come across a package that ought to use it (display-buffer), but doesn't conform, chances are you'll have to speak with upstream instead of me to have it fixed.
