### ISSUE TITLE
Disabling for Tuareg (OCaml REPL) and make

### ISSUE THREAD

**Issue by rotsix** [wasamasa/shackle#45]
Hi!

Could you show me how i can disable shackle for some specifics buffers (like *OCaml*, or *Make*,..) ?

Thanks!
regards,
rotsix

**Comment by wasamasa** [comment]
Shackle is a global minor mode as it modified `display-buffer-alist'.  Ideally you write your rules so that none of them matches the OCaml or Make buffer.  If this isn't possible for some reason, you can instead create a rule without actions matching it, such as `("makefile\\'" :regex t)`.

**Comment by rotsix** [comment]
Thanks! I'll take a look 👍
