### ISSUE TITLE
Calculator Mode

### ISSUE THREAD

**Issue by sk8ingdom** [wasamasa/shackle#47]
I've tried all of the following in shackle-rules but can't seem to get shackle to work with calc-mode:

    (calc-mode                       :align below :select t)
    (" *Calculator*"                 :align below :select t)
    ("*Calculator*"                  :align below :select t)
    ("*Calc Trail"                   :align below :select t)

Running `M-x calc` seems to produce a *Calculator* buffer within another window, seemingly arbitrarily.

Ideally running calc would change windows from this:

    | Window 1 | Window 2 |
    |          |          |
    |          |          |
    |          |          |
    |----------+----------|
    | Window 3            |
    |---------------------|

to this:

    | Window 1 | Window 2 |
    |          |          |
    |----------+----------|
    | Window 3            |
    |----------+----------|
    | Calc     | Tail     |
    |----------+----------|

Any ideas? I'm definitely willing to put in some of the leg work if necessary!

**Comment by wasamasa** [comment]
I've finally implemented a way to trace `display-buffer` to make debugging this kind of stuff easier.  If you do `M-x shackle-trace-functions`, open the calculator and check the "*shackle trace*" buffer you'll see no trace of calculator buffers whatsoever.  It's therefore impossible for this package to do anything about it.  Hand in an Emacs bug if you care, I most certainly don't.
