### ISSUE TITLE
Feature request: new :fit option for rules

### ISSUE THREAD

**Issue by jwiegley** [wasamasa/shackle#48]
If a rule specifies `:fit t`, then fit the window size to the buffer contents.  If `:size` is also specified, this becomes a maximum size for the buffer, but it may be smaller after fitting.

**Comment by wasamasa** [comment]
I'm not entirely sure on the semantics of this one.  Is it intended to be used additionally to an action that creates a split window, much like `:select`?

**Comment by jwiegley** [comment]
I guess a more fundamental feature request would be: Support an `:after` hook, which specifies a function that will be called within the buffer+window being controlled by shackle after it is displayed.  Then `:fit` is just `:after fit-window-to-buffer`.

**Comment by wasamasa** [comment]
This is known as `after` advice. Also, it wouldn't fix the problem mentioned above.

**Comment by jwiegley** [comment]
It's not exactly the same as `after` advice, though, right, because how will I know which window the advice is being executed in?  I want it to happen in the popup window in question, after the window showing it has come into existence.  We can chat more in IRC another day.

**Comment by Fuco1** [comment]
I would also like the have the `:after` option in some form.  Some of the popups I open I would like to align to the bottom of the *entire* frame even if I'm in a split, so that

```
+----------------------+----------------------+
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
+----------------------+----------------------+
```

becomes

```
+----------------------+----------------------+
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
|                      |                      |
+---------------------------------------------+
|                                             |
|                                             |
+----------------------+----------------------+
```

That can be achieved by calling `elwm-shift-down` (from my https://github.com/Fuco1/elwm package) once the window is created and selected.

**Comment by wasamasa** [comment]
@Fuco1 That looks like what the `:align` action does. Did you try that one?

**Comment by Fuco1** [comment]
@wasamasa I'm 90% sure that only works within the split but I did not try it, will do.
