### ISSUE TITLE
Is it possible to override such a call?

### ISSUE THREAD

**Issue by usharf** [wasamasa/shackle#50]
```emacs-lisp
(display-buffer
       buffer
       '(nil (inhibit-same-window . t))
```

I'd like to override such a call (in a 3rd party mode) with an `advice` or some other way in code.

**Comment by wasamasa** [comment]
This is a case where TIAS would have given you the answer instantly.  Given a config of `(setq shackle-rules '(("XXX" :regex t :align t)))` the following spawns an aligned window:

```
(display-buffer (get-buffer-create "*XXX*") '(nil (inhibit-same-window . t)))
```

**Comment by usharf** [comment]
Thank you. 

* Sorry for my “courtness”   — appreciate you taking the time.
