### ISSUE TITLE
How to leave magit display as it was?

### ISSUE THREAD

**Issue by JJPandari** [wasamasa/shackle#56]
I want to let magit display its buffers *as it was*, that is, before I added shackle. `("magit" :regexp t :ignore t)` doesn't do this. I saw some people reconfigure each type of magit buffer to get expected display, but that doesn't get `magit-display-buffer-fullframe-status-v1` for me, AFAIK, shackle doesn't provide fullframe display as an option currently. FYI, I used `(setq magit-display-buffer-function 'magit-display-buffer-fullframe-status-v1)` for magit.  

I tried to `push` something to the head of `display-buffers-alist`, but wasn't experienced enough to really get it working. Also, the way some people do, reconfiguring each type of magit buffer, doesn't look neat, though mostly fixes the problem.  

I think this could be a common issue and it'd be nice if you provide more guide in the readme (currently it's just the problem being mentioned).

**Comment by wasamasa** [comment]
Please provide a minimal reproduction example showing the broken and the expected behavior because I have absolutely no idea what exactly your problem is.

**Comment by JJPandari** [comment]
I fixed my problem by setting `shackle-default-rule` to `nil`. This way no magit display is affected.
