### ISSUE TITLE
:select incompatible with the latest powerline active window

### ISSUE THREAD

**Issue by zhangpj** [wasamasa/shackle#59]
`shackle-display-buffer` calls `select-window` with the second argument `norecord` non-`nil` (https://github.com/wasamasa/shackle/blob/master/shackle.el#L456). This is incompatible the active window system of powerline due to a recent change https://github.com/milkypostman/powerline/commit/53a2c3b5af243021f85bc452cbebd01d87fd3d95, and maybe other functions relying on `buffer-list-update-hook`.

 Is there any reason for using a non-`nil` value for `norecord` argument of the `select-window` function? I feel like `:select` does not mean a temporary change of window so `norecord` should be `nil`.

Thanks!

**Comment by wasamasa** [comment]
Hm, good question. I've tried borrowing as much as possible from the original function in window.el, but now that I'm checking them again, they aren't using the `norecord` argument either.
