### ISSUE TITLE
Inhibit close for existing windows

### ISSUE THREAD

**Issue by buhudu** [wasamasa/shackle#60]
Is there a way to set inhibit-window-quit to t only if the popup reuses an existing window?

If shackle opens a new window, I'd like to quit that window when I close the popup, but if it reuses an existing window, I don't want that window to close. Seems like this should be pretty simple, but I can't figure it out.

**Comment by wasamasa** [comment]
No, there is no easy way to do this. Use a custom action to apply `inhibit-window-quit` on a more granular basis.
