### ISSUE TITLE
shackle-rules require :align for :size to work

### ISSUE THREAD

**Issue by fikovnik** [wasamasa/shackle#63]
I think I do something wrong. I have the following configuration to let shackle manage _Flycheck errors_ buffer.

```elisp
(use-package shackle
  :custom
  (shackle-default-alignment 'below)
  (shackle-default-size 0.5)
  (shackle-default-rule '(:select t))
  (shackle-rules '((flycheck-error-list-mode  :select t :size 0.15 :popup t)))
  :config
  (shackle-mode 1))
```

It works, except for the window size - it will just split the current frame in half. It only works when I add `:align 'below` to configuration:

```elisp
(shackle-rules '((flycheck-error-list-mode  :select t :size 0.15 :popup t :align 'below)))
```

I thought that if the `:align` is missing the default will be used. Also does not seem to me to be related to window size. Is this an issue or I miss something?

**Comment by wasamasa** [comment]
To use the default alignment you need to specify `:align t`.
