### ISSUE TITLE
Order of :align and :size keywords

### ISSUE THREAD

**Issue by jumper047** [wasamasa/shackle#64]
In my config rule ("*vc-dir*" :size 0.4 :align right) works fine, but  ("*vc-dir*":align right  :size 0.4 ) not. Is it something wrong with my config, or readme, which describes second variant of keywords order?

**Comment by wasamasa** [comment]
These are equivalent to each other, so my guess is you aren't testing properly. Please provide a minimal reproduction example still triggering this behavior.

**Comment by jumper047** [comment]
Sorry, seems like it was mistype somewhere, or some complex issue with my config. I cannot reproduce it now.
