### ISSUE TITLE
[Question] term and vterm

### ISSUE THREAD

**Issue by seagle0128** [wasamasa/shackle#66]
Hi, I am enjoying the amazing `shackle` package. 

Would you please guide me how to set for `term-mode` and `vterm-mode` (or `*terminal*` and `vterm` buffers?) I want to make the window align below, but didn't work with my codes.

Thanks!

**Comment by wasamasa** [comment]
The package includes some debugging helpers to tell what kind of rule to apply to them:

- `M-x shackle-trace-functions`
- Reproduce the thing popping up a window
- Check the trace buffer for something displaying the popped up buffer

If there's a matching line, it will tell you what to match for and you can use that in your config. However if there's no matching line in it, there's nothing you can do, other than handing in a bug report asking for the author to use the equivalent helper function using `display-buffer` internally. This seems to be the case for `term-mode` as it's using `switch-to-buffer`. It should be using `pop-to-buffer-same-window` instead. I can't test for `vterm-mode`, possibly it's the same for it.

**Comment by seagle0128** [comment]
Thank you!
