### ISSUE TITLE
:popup does not work with eshell-mode

### ISSUE THREAD

**Issue by yurikoif** [wasamasa/shackle#67]
Strangely the issue gets solved by just using `:regexp` as the author suggested in [https://emacs.stackexchange.com/questions/51060/how-do-i-create-a-popup-window](url). But I still wonder why `eshell-mode` does not work here.

---------------------------------------------
`:popup` does not seem to work with `eshell-mode`, where I expected `M-x eshell` would popup an eshell window aligned as I set it up. If it is not an issue, could one tell me what I did wrong? Thanks.

**Comment by wasamasa** [comment]
Here's the relevant code from `eshell`:

```elisp
    (pop-to-buffer-same-window buf)
    (unless (derived-mode-p 'eshell-mode)
      (eshell-mode))
```

`eshell-mode` is enabled *after* the buffer is displayed, so there's no way specifying that as condition will work. You've already figured out the solution, match on the buffer name with a regular expression.
