### ISSUE TITLE
Confusion about using shackle with a major mode

### ISSUE THREAD

**Issue by Nathan-Furnal** [wasamasa/shackle#68]
Hi,

I'm doing the following : writing stuff in org-mode and displaying it in PDF with ``pdf-tools`` once exported. It always opens a window below while I'd like it to be on the right, the major mode, as far as I'm aware is called ``pdf-view-mode``.

I tried to use ``shackle`` like this : 

```
(use-package shackle
  :ensure t
  :defer t
  :config
  (setq shackle-rules '((pdf-view-mode :align 'right)))
  (shackle-mode)
  )

```

But it doesn't work and the output of pdf-tools is still displayed below my current org file.

What am I doing wrong?

thanks

**Comment by wasamasa** [comment]
There's at least one problem with this config, don't use quotes inside quotes unless you know what you're doing. Instead of `'((pdf-view-mode :align 'right))` it should be`'((pdf-view-mode :align right))`.

That aside there's a different issue. You write mostly about pdf-tools and pdf-view-mode, but the code triggering the displayed buffer is from org-mode. Use `M-x shackle-trace-functions` to figure out whether there's a chance at all for shackle to influence org-mode's logic for displaying buffers and share the log contents mentioning the relevant buffer. Alternatively, provide a minimized set of reproduction instructions.

**Comment by Nathan-Furnal** [comment]
@wasamasa Thanks for the correction, I'm very new to ELisp and still trying to get the hang of it.
After your correction, pdf-view-mode displays on the right as I wished !

Here is the stack trace, I'm not familiar with schackle either so I'm not sure it there's something fisy here or not? In any case it works.

Thanks for your time

```
======================================================================
1 -> (switch-to-buffer-other-window #<buffer *Org Export Dispatcher*>)
| 2 -> (pop-to-buffer #<buffer *Org Export Dispatcher*> t nil)
| | 3 -> (display-buffer #<buffer *Org Export Dispatcher*> t)
| | 3 <- display-buffer: #<window 14 on *Org Export Dispatcher*>
| 2 <- pop-to-buffer: #<buffer *Org Export Dispatcher*>
1 <- switch-to-buffer-other-window: #<buffer *Org Export Dispatcher*>
======================================================================
1 -> (display-buffer #<buffer *Org PDF LaTeX Output*> nil nil)
1 <- display-buffer: #<window 16 on *Org PDF LaTeX Output*>
======================================================================
1 -> (display-buffer #<buffer *Org PDF LaTeX Output*> nil nil)
1 <- display-buffer: #<window 16 on *Org PDF LaTeX Output*>
======================================================================
1 -> (display-buffer #<buffer *Org PDF LaTeX Output*> nil nil)
1 <- display-buffer: #<window 16 on *Org PDF LaTeX Output*>
======================================================================
1 -> (switch-to-buffer-other-window #<buffer develop.pdf>)
| 2 -> (pop-to-buffer #<buffer develop.pdf> t nil)
| | 3 -> (display-buffer #<buffer develop.pdf> t)
| | 3 <- display-buffer: #<window 18 on develop.pdf>
| 2 <- pop-to-buffer: #<buffer develop.pdf>
1 <- switch-to-buffer-other-window: #<buffer develop.pdf>
======================================================================
1 -> (display-buffer #<buffer *Buffer List*>)
1 <- display-buffer: #<window 3 on *Buffer List*>
```

**Comment by wasamasa** [comment]
That looks fine to me. I've had cases where org-mode did deliberately override `display-buffer-alist` and therefore disabled user customization, but this doesn't seem to happen here.

**Comment by Nathan-Furnal** [comment]
@wasamasa glad to hear it, thanks for the package!
